name: Meshkit Error Codes Utility Runner
on:
  push:
    branches:
      - 'master'
    paths:
      - '**.go'

jobs:
  Update-error-codes:
    name: Error codes utility
    if: github.repository == 'meshplay/meshplay-cilium'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      # token here with write access to meshplay-cilium repo
        with:
          token: ${{ secrets.GH_ACCESS_TOKEN }}
          ref: 'master'

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Run utility
        run: |
          go get github.com/khulnasoft/meshkit/cmd/errorutil
          go run github.com/khulnasoft/meshkit/cmd/errorutil -d . update --skip-dirs meshplay -i ./helpers -o ./helpers
      # to update errorutil* files in meshplay-cilium repo
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_user_name: l5io
          commit_user_email: ci@layer5.io
          commit_author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          commit_options: '--signoff'
          commit_message: "run error codes utility"
          file_pattern: helpers/ **error.go

      # to push changes to meshplay docs
      - name: Checkout meshplay
        uses: actions/checkout@master
        with:
          repository: 'meshplay/meshplay'
          # token with write access to meshplay repository
          token: ${{ secrets.GH_ACCESS_TOKEN }}
          path: 'meshplay'
          ref: 'master'

      - name: Update docs
        run: |
          echo '{ "errors_export": "" }' | jq --slurpfile export ./helpers/errorutil_errors_export.json '.errors_export = $export[0]' > ./meshplay/docs/_data/errorref/cilium_errors_export.json
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          repository: ./meshplay
          commit_user_name: l5io
          commit_user_email: ci@layer5.io
          commit_author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          commit_options: '--signoff'
          commit_message: '[Docs] Error Code Reference: Meshplay Adapter for Cilium updated'
          file_pattern: docs/